name: Codecov workflow
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@master
      - name: Setup Node
      - uses: actions/setup-node@latest
      - name: Install requirements
      - run: npm install
      - name: Run tests & collect coverage
      - run: npm run test
      - name: Upload coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
